--- #YAML:1.0
name:                Senna
version:             0.51
abstract:            Interface to Senna search engine
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Daisuke Maki <dmaki@cpan.org>
