---
name: Senna
version: 0.12
author:
  - 'Copyright (C) 2005 by Daisuke Maki <dmaki@cpan.org>'
abstract: Perl Interface To Senna Fulltext Search Engine
license: lgpl
provides:
  Senna:
    file: lib/Senna.pm
    version: 0.12
  Senna::Cursor:
    file: lib/Senna/Cursor.pm
    version: 0.01
  Senna::Index:
    file: lib/Senna/Index.pm
    version: 0.03
  Senna::Result:
    file: lib/Senna/Result.pm
generated_by: Module::Build version 0.2612
