---
name: Senna
version: 0.02
author:
  - Copyright (C) 2005 by Daisuke Maki <dmaki@cpan.org>
abstract: Perl Interrface To Senna Fulltext Search Engine
license: perl
provides:
  Senna:
    file: lib/Senna.pm
    version: 0.02
  Senna::Cursor:
    file: lib/Senna/Cursor.pm
    version: 0.01
  Senna::Index:
    file: lib/Senna/Index.pm
    version: 0.02
  Senna::Result:
    file: lib/Senna/Result.pm
generated_by: Module::Build version 0.261
